AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template

Parameters:
  RootDomainName:
    Description: Domain name for your website (example.com)
    Type: String
    Default: cupel.io

Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
          - app.${Domain}
          - Domain: !Ref RootDomainName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
